#ifndef INTERFACE_H
#define INTEFACE_H

// menu
#define MENU_RED 0.3
#define MENU_GREEN 0.5
#define MENU_BLUE 0.8
#define START_BUTTON_WIDTH 200
#define START_BUTTON_HEIGHT 100

// main application
#define MAIN_APP_RED 0.8
#define MAIN_APP_GREEN 0.8
#define MAIN_APP_BLUE 0.8


// color button
#define COLOR_BOTTON_WIDTH 50
#define COLOR_BOTTON_HEIGHT 50

// draw circles button
#define DRAW_CIRCLES_BUTTON_WIDTH 50
#define DRAW_CIRCLES_BUTTON_HEIGHT 50
#define DRAW_CIRCLES_BUTTON_COLOR_R 1
#define DRAW_CIRCLES_BUTTON_COLOR_G 0.2
#define DRAW_CIRCLES_BUTTON_COLOR_B 1

// cancel function button
#define CANCEL_FUNCTION_BUTTON_WIDTH 50
#define CANCEL_FUNCTION_BUTTON_HEIGHT 50
#define CANCEL_FUNCTION_BUTTON_R 1
#define CANCEL_FUNCTION_BUTTON_G 0
#define CANCEL_FUNCTION_BUTTON_B 0

// radius plus button
#define RADIUS_PLUS_BUTTON_WIDTH 40
#define RADIUS_PLUS_BUTTON_HEIGHT 40
#define RADIUS_PLUS_BUTTON_R 0
#define RADIUS_PLUS_BUTTON_G 1
#define RADIUS_PLUS_BUTTON_B 0

// radius minus button
#define RADIUS_MINUS_BUTTON_WIDTH 40
#define RADIUS_MINUS_BUTTON_HEIGHT 40
#define RADIUS_MINUS_BUTTON_R 1
#define RADIUS_MINUS_BUTTON_G 0
#define RADIUS_MINUS_BUTTON_B 0
#define RADIUS_INCREASE_DECREASE 10

// sides plus button
#define SIDES_PLUS_BUTTON_WIDTH 40
#define SIDES_PLUS_BUTTON_HEIGHT 40
#define SIDES_PLUS_BUTTON_R 0
#define SIDES_PLUS_BUTTON_G 1
#define SIDES_PLUS_BUTTON_B 0
#define SIDES_INCREASE_DECREASE 1

// sides minus button
#define SIDES_MINUS_BUTTON_WIDTH 40
#define SIDES_MINUS_BUTTON_HEIGHT 40
#define SIDES_MINUS_BUTTON_R 1
#define SIDES_MINUS_BUTTON_G 0
#define SIDES_MINUS_BUTTON_B 0

// preview
#define PREVIEW_X_PERCENT 10
#define PREVIEW_Y_PERCENT 10
#define PREVIEW_RADIUS_DIV 5

// figure selected colors
#define FIGURE_SELECTED_R 0
#define FIGURE_SELECTED_G 0.8
#define FIGURE_SELECTED_B 0.8


#endif // INTERFACE_H
